/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import base.Usuario;
import bd.UsuarioDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author igorp
 */
public class TelaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdministrador
     */
    public TelaAdministrador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CBOpcao = new javax.swing.JComboBox<>();
        BtnOK = new javax.swing.JButton();
        LblUsuario = new javax.swing.JLabel();
        TFUsuario = new javax.swing.JTextField();
        LblNome = new javax.swing.JLabel();
        TFNome = new javax.swing.JTextField();
        LblEmail = new javax.swing.JLabel();
        LblDtNascimento = new javax.swing.JLabel();
        TFEmail = new javax.swing.JTextField();
        TFDtNascimento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TASaida = new javax.swing.JTextArea();
        BtnFinal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TELA DE ADMINISTRAÇÃO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ESCOLHA A OPÇÃO DESEJADA:");

        CBOpcao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CBOpcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listar Usuários", "Deletar Usuário", "Atualizar Usuário" }));
        CBOpcao.setSelectedIndex(-1);

        BtnOK.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnOK.setText("OK");
        BtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOKActionPerformed(evt);
            }
        });

        LblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LblUsuario.setText("USUÁRIO:");
        LblUsuario.setEnabled(false);

        TFUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TFUsuario.setEnabled(false);

        LblNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LblNome.setForeground(new java.awt.Color(255, 255, 255));
        LblNome.setText("NOME:");
        LblNome.setEnabled(false);

        TFNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TFNome.setEnabled(false);

        LblEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LblEmail.setForeground(new java.awt.Color(255, 255, 255));
        LblEmail.setText("E-MAIL:");
        LblEmail.setEnabled(false);

        LblDtNascimento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LblDtNascimento.setForeground(new java.awt.Color(255, 255, 255));
        LblDtNascimento.setText("DATA DE NASCIMENTO:");
        LblDtNascimento.setEnabled(false);

        TFEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TFEmail.setEnabled(false);

        TFDtNascimento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TFDtNascimento.setEnabled(false);

        TASaida.setEditable(false);
        TASaida.setColumns(20);
        TASaida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TASaida.setRows(5);
        jScrollPane1.setViewportView(TASaida);

        BtnFinal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnFinal.setEnabled(false);
        BtnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(402, 402, 402))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblDtNascimento)
                            .addComponent(LblEmail)
                            .addComponent(LblNome)
                            .addComponent(LblUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                            .addComponent(TFUsuario)
                            .addComponent(TFNome)
                            .addComponent(TFEmail)
                            .addComponent(TFDtNascimento))
                        .addGap(18, 18, 18)
                        .addComponent(BtnFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(CBOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblUsuario)
                    .addComponent(BtnFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblNome))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDtNascimento)
                    .addComponent(TFDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOKActionPerformed
        int resultadoCB = CBOpcao.getSelectedIndex();
        switch(resultadoCB){
            case 0:
                //Listar Usuários;
                List<Usuario> usuarios = new ArrayList<Usuario>();
                UsuarioDAO usuariodao = new UsuarioDAO();

                usuarios = usuariodao.listarUsuarios();
                String resultado = "Lista de usuarios:\n";
                int contador = 1;
                for (Usuario u : usuarios){
                    resultado += "Usuario "+contador+" : "+ u.getUsuario()+"\n";
                    contador++;
                }
                
                TASaida.setText(resultado);
                break;
            case 1:
                //Deletar Usuário.
                LblUsuario.setEnabled(true);
                TFUsuario.setEnabled(true);
                BtnFinal.setEnabled(true);
                BtnFinal.setText("DELETAR");
                break;
            case 2:
                //Atualizar Usuário.
                LblUsuario.setEnabled(true);
                TFUsuario.setEnabled(true);
                BtnFinal.setEnabled(true);
                BtnFinal.setText("ATUALIZAR");
                LblEmail.setEnabled(true);
                TFEmail.setEnabled(true);
                LblNome.setEnabled(true);
                TFNome.setEnabled(true);
                LblDtNascimento.setEnabled(true);
                TFDtNascimento.setEnabled(true);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Escolha uma opção!");
        }
        
        
    }//GEN-LAST:event_BtnOKActionPerformed

    private void BtnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinalActionPerformed
        if (BtnFinal.getText().equals("DELETAR")){
            String usuario = TFUsuario.getText();
            UsuarioDAO usuariodao = new UsuarioDAO();
            usuariodao.removerporUsuario(usuario);
        }
    }//GEN-LAST:event_BtnFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFinal;
    private javax.swing.JButton BtnOK;
    private javax.swing.JComboBox<String> CBOpcao;
    private javax.swing.JLabel LblDtNascimento;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblNome;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JTextArea TASaida;
    private javax.swing.JTextField TFDtNascimento;
    private javax.swing.JTextField TFEmail;
    private javax.swing.JTextField TFNome;
    private javax.swing.JTextField TFUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
